name: Client deployment

on:
  push:
    branches:
      - main

jobs:
  provision:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.6

    - name: Terraform Initialize
      run: terraform init

    - name: Terraform Validate
      run: terraform validate -no-color

    - name: Terraform Plan
      run: terraform plan -no-color

    - name: Terraform Apply
      run: terraform apply -auto-approve
  
  deploy-client:
    runs-on: ubuntu-latest
    needs: [provision]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get API URL
        id: get_url
        run: echo "::set-output name=api_url::$(terraform output -raw api_url)"
      - name: Get Deployment Bucket
        id: get_bucket
        run: echo "::set-output name=bucket::$(terraform output -raw deployment_bucket)"

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
        working-directory: ./client
      - name: Install Dependencies
        run: flutter pub get
        working-directory: ./client

      - name: Build Web App
        run: flutter build web --web-renderer html --release
        working-directory: ./client
        env:
          API_URL: ${{ steps.get_url.outputs.api_url }}
      - name: Modify Index HTML
        run: |
          # Navigate to the directory containing the index.html file
          cd build/web

          # Replace <base href="/"> with <base href="./">
          sed -i 's/<base href="\/">/<base href=".\/">/' index.html
        working-directory: ./client

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ steps.get_bucket.outputs.bucket }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'   # optional: defaults to us-east-1
          SOURCE_DIR: './client/build/web'
          DEST_DIR: 'deployment/'